remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins

title: Nabeel Khan 
description: Analytical Professional

show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]
